import type { ReactNode } from "react";
import { ArrowUpRight, CheckCircle2, CircleAlert, Minus } from "lucide-react";
import type { OrbisObject } from "@/lib/orbis";

export function PageHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: ReactNode }) { return <div data-testid="page-header" className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><div data-testid="page-header-eyebrow" className="font-mono text-[10px] tracking-[0.2em] text-cyan-300">{eyebrow}</div><h1 data-testid="page-header-title" className="mt-2 font-heading text-3xl font-black tracking-tight text-white sm:text-4xl">{title}</h1><p data-testid="page-header-description" className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">{description}</p></div>{action}</div>; }
export function Panel({ title, eyebrow, children, className = "" }: { title: string; eyebrow?: string; children: ReactNode; className?: string }) { return <section data-testid={`panel-${title.toLowerCase().replaceAll(" ", "-")}`} className={`rounded-lg border border-slate-800/90 bg-[#0b1220]/80 shadow-2xl ${className}`}><div className="flex items-center justify-between border-b border-slate-800/80 px-4 py-3"><div><div data-testid="panel-eyebrow" className="font-mono text-[9px] tracking-[0.18em] text-slate-600">{eyebrow || "ORBIS TELEMETRY"}</div><h2 data-testid="panel-title" className="mt-1 text-sm font-semibold text-slate-200">{title}</h2></div><span className="h-1 w-8 bg-cyan-400/60" /></div><div className="p-4">{children}</div></section>; }
export function MetricCard({ label, value, hint, tone = "cyan" }: { label: string; value: string | number; hint?: string; tone?: "cyan" | "amber" | "red" | "green" }) { const colors = { cyan: "text-cyan-300 border-cyan-400/20", amber: "text-amber-300 border-amber-400/20", red: "text-red-300 border-red-400/20", green: "text-emerald-300 border-emerald-400/20" }; return <div data-testid={`metric-card-${label.toLowerCase().replaceAll(" ", "-")}`} className={`rounded-lg border bg-[#0b1220] p-4 ${colors[tone]}`}><div data-testid="metric-card-label" className="font-mono text-[9px] tracking-[0.16em] text-slate-500">{label}</div><div data-testid="metric-card-value" className="mt-3 font-mono text-2xl font-bold tracking-tight">{value}</div>{hint ? <div data-testid="metric-card-hint" className="mt-1 text-[10px] text-slate-600">{hint}</div> : null}</div>; }
export function StatusChip({ value }: { value: string | null | undefined }) { const text = value || "N/A"; const isGood = ["FAST", "RELIABLE", "CLEAR", "OPERATIONAL", "OK"].includes(text); const isBad = ["LOW_CONFIDENCE", "POTENTIAL_CONJUNCTION", "ERROR", "DEGRADED"].includes(text); return <span data-testid={`status-chip-${text.toLowerCase().replaceAll("_", "-")}`} className={`inline-flex items-center gap-1 rounded border px-2 py-1 font-mono text-[9px] tracking-wider ${isGood ? "border-emerald-400/20 bg-emerald-400/5 text-emerald-300" : isBad ? "border-red-400/20 bg-red-400/5 text-red-300" : "border-amber-400/20 bg-amber-400/5 text-amber-300"}`}>{isGood ? <CheckCircle2 size={11} /> : isBad ? <CircleAlert size={11} /> : <Minus size={11} />}{text}</span>; }
export function ObjectRow({ object, onSelect }: { object: OrbisObject; onSelect?: () => void }) { return <tr data-testid={`object-row-${object.id}`} onClick={onSelect} className="cursor-pointer border-b border-slate-800/60 text-xs hover:bg-cyan-400/5"><td className="px-4 py-3 font-mono text-cyan-300">{object.id}</td><td className="max-w-[220px] truncate px-4 py-3 text-slate-200">{object.name || "UNNAMED OBJECT"}</td><td className="px-4 py-3 text-slate-500">{object.type || "N/A"}</td><td className="px-4 py-3 font-mono text-slate-300">{object.aci?.toFixed(3) || "N/A"}</td><td className="px-4 py-3"><StatusChip value={object.decision} /></td><td className="px-4 py-3 font-mono text-slate-300">{object.model_confidence != null ? `${(object.model_confidence * 100).toFixed(1)}%` : "N/A"}</td><td className="px-4 py-3"><StatusChip value={object.ml_prediction} /></td><td className="px-4 py-3 font-mono text-slate-400">{object.data_age_days != null ? `${object.data_age_days.toFixed(1)}d` : "N/A"}</td><td className="px-4 py-3 font-mono text-slate-500">{object.prediction_error_km != null ? `${object.prediction_error_km.toFixed(2)} km` : "N/A"}</td><td className="px-4 py-3"><ArrowUpRight size={14} className="text-slate-600" /></td></tr>; }
export function ObjectTable({ objects, onSelect }: { objects: OrbisObject[]; onSelect: (id: string) => void }) { return <div data-testid="object-table" className="overflow-x-auto rounded-lg border border-slate-800"><table className="w-full min-w-[980px] text-left"><thead className="bg-slate-900/80 font-mono text-[9px] uppercase tracking-wider text-slate-500"><tr>{["ID", "Name", "Type", "ACI", "Decision", "Model confidence", "ML prediction", "Data age", "Prediction error", ""].map((head) => <th data-testid={`object-table-header-${head.toLowerCase().replaceAll(" ", "-")}`} key={head} className="px-4 py-3">{head}</th>)}</tr></thead><tbody>{objects.map((object) => <ObjectRow key={object.id} object={object} onSelect={() => onSelect(object.id)} />)}</tbody></table></div>; }
export function EmptyState({ message }: { message: string }) { return <div data-testid="empty-state" className="rounded border border-dashed border-slate-800 p-10 text-center font-mono text-xs text-slate-600">{message}</div>; }
export function DetailValue({ label, value }: { label: string; value: ReactNode }) { return <div data-testid={`detail-value-${label.toLowerCase().replaceAll(" ", "-")}`} className="border-b border-slate-800/70 py-3"><div className="font-mono text-[9px] uppercase tracking-wider text-slate-600">{label}</div><div className="mt-1 text-sm text-slate-200">{value}</div></div>; }