import { useNavigate } from "react-router-dom";
import { Crosshair, ArrowUpRight, Eye, EyeOff, ScanLine, Satellite, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { DetailValue, StatusChip, DataState } from "./ConsolePrimitives";
import { number, percent, utc, useHistory } from "@/lib/data";
import type { ObjectData } from "@/lib/data";
import { useOrbisStore } from "@/lib/store";
import ObjectVisual from "./ObjectVisual";

export function ReliabilityContext(){return <div data-testid="reliability-context" className="border-l-2 border-cyan-500/30 bg-cyan-500/[.03] px-3 py-2.5"><div className="technical-label text-cyan-200">RELIABILITY CONTEXT</div><p className="mt-1 text-[10px] leading-5 text-slate-400">ACI and ML describe confidence in the available evidence. They are not collision probabilities or guarantees of orbital safety.</p><div data-testid="model-status" className="mt-2 font-mono text-[8px] text-slate-300">MODEL STATUS / CALIBRATED PROTOTYPE</div><p className="mt-1 text-[9px] text-slate-500">Existing backend model outputs. Independent ground-truth validation is not established.</p></div>;}

export default function ObjectIntelligence({data}:{data:ObjectData}){
  const navigate=useNavigate();const {selectedObjectId,setSelectedObject,orbitVisible,setOrbitVisible,focusObject,live}=useOrbisStore();
  const history=useHistory();const last=!history.isError?history.data?.items.find(h=>h.target_id===selectedObjectId):undefined;
  const o=!data.object.isError?data.object.data:undefined;const state=data.current;
  return <aside data-testid="selected-object-panel" className="console-panel flex min-w-0 flex-col"><div className="flex items-center justify-between border-b border-slate-800 px-4 py-3"><div><div className="technical-label">OBJECT INTELLIGENCE</div><div data-testid="selected-panel-status" className="mt-1 text-[11px] text-slate-400">{selectedObjectId?"Selected catalog object":"Awaiting selection"}</div></div>{selectedObjectId?<Button data-testid="clear-selected-object-button" title="Clear selection" variant="ghost" size="icon-xs" onClick={()=>setSelectedObject(null)}><X size={13}/></Button>:<Crosshair size={16} className="text-slate-500"/>}</div>
    {!selectedObjectId?<div data-testid="selection-empty-state" className="flex min-h-[450px] flex-1 flex-col items-center justify-center px-7 text-center"><div className="relative mb-5 grid h-20 w-20 place-items-center rounded-full border border-dashed border-cyan-500/25"><Satellite size={26} className="text-cyan-300/65"/><span className="absolute -right-1 top-3 h-2 w-2 rounded-full bg-cyan-200/80"/></div><h3 className="font-heading text-lg text-slate-200">Acquire an object</h3><p className="mt-2 text-xs leading-6 text-slate-500">Select a catalog marker on Earth or search by name and NORAD ID to inspect its orbital state.</p><Button data-testid="selection-browse-catalog" variant="outline" size="sm" className="mt-6 font-mono text-[9px]" onClick={()=>navigate("/objects")}>BROWSE CATALOG <ArrowUpRight size={11}/></Button><p className="mt-10 font-mono text-[8px] leading-5 tracking-wider text-slate-500">SGP4 POSITION · ACI CONFIDENCE<br/>ML RELIABILITY · GEOMETRIC SCREENING</p></div>:<div className="p-4"><DataState error={data.object.isError} loading={data.object.isLoading} retry={()=>data.object.refetch()} message="ACQUIRING OBJECT DATA"/>{o?<div className="fade-enter" key={o.id}><div className="mb-3"><div data-testid="selected-object-id" className="font-mono text-[9px] text-cyan-300">CATALOG / {o.id}</div><h3 data-testid="selected-object-name" className="mt-1 break-words font-heading text-xl text-slate-100">{o.name||"UNNAMED OBJECT"}</h3><div data-testid="selected-object-type" className={`mt-1 font-mono text-[9px] ${o.type==="Debris"?"text-amber-300":"text-slate-400"}`}>{o.type?.toUpperCase()||"UNCLASSIFIED"}</div></div><ObjectVisual key={o.id} object={o}/>
    <Tabs defaultValue="state" className="mt-3"><TabsList data-testid="intelligence-tabs" variant="line" className="w-full"><TabsTrigger data-testid="intelligence-state-tab" value="state" className="flex-1 text-[10px]">State</TabsTrigger><TabsTrigger data-testid="intelligence-quality-tab" value="quality" className="flex-1 text-[10px]">Reliability</TabsTrigger><TabsTrigger data-testid="intelligence-source-tab" value="source" className="flex-1 text-[10px]">Source</TabsTrigger></TabsList><TabsContent value="state"><div data-testid="selected-state-grid" className="grid grid-cols-2 gap-x-3"><DetailValue label="Latitude" value={number(state?.latitude_deg,3,"°")}/><DetailValue label="Longitude" value={number(state?.longitude_deg,3,"°")}/><DetailValue label="Altitude" value={number(state?.altitude_km,2," km")}/><DetailValue label="Speed" value={number(state?.speed_km_s,3," km/s")}/></div><div className="mt-3 flex items-center justify-between"><span className="technical-label">{live?"CURRENT STATE":"REPLAY SAMPLE"}</span><StatusChip value={state?.sgp4_status}/></div><p data-testid="selected-state-epoch" className="mt-2 font-mono text-[8px] text-slate-500">{utc(state?.utc)}</p></TabsContent><TabsContent value="quality"><div className="grid grid-cols-2 gap-x-3"><DetailValue label="ACI" value={number(o.aci,4)}/><DetailValue label="Decision" value={<StatusChip value={o.decision}/>}/><DetailValue label="Model confidence" value={percent(o.model_confidence)}/><DetailValue label="ML prediction" value={<StatusChip value={o.ml_prediction}/>}/><DetailValue label="Data age" value={number(o.data_age_days,2," d")}/><DetailValue label="Trajectory consistency" value={number(o.trajectory_consistency,4)}/></div><DetailValue label="Prediction error" value={<><span data-testid="selected-prediction-error">{number(o.prediction_error_km,3," km")}</span>{o.prediction_error_km==null?<p className="mt-1 font-sans text-[9px] text-slate-500">No valid live/reference comparison available.</p>:null}</>}/><div className="mt-3"><ReliabilityContext/></div></TabsContent><TabsContent value="source"><DetailValue label="TLE epoch" value={o.epoch||"N/A"}/><DetailValue label="Prediction horizon" value={number(o.prediction_horizon_hours,1," h")}/><p data-testid="selected-tle-line-one" className="mt-3 break-all font-mono text-[9px] leading-5 text-slate-400">{o.tle_line1||"TLE UNAVAILABLE"}</p><p data-testid="selected-tle-line-two" className="mt-2 break-all font-mono text-[9px] leading-5 text-slate-400">{o.tle_line2}</p></TabsContent></Tabs>
    <div className="mt-4 border-y border-slate-800 py-3"><div className="mb-2 technical-label">{last?"LAST SAVED SCREENING":"CONJUNCTION CONTEXT"}</div><StatusChip value={last?.status||"NOT_SCREENED"}/>{last?<p className="mt-1 font-mono text-[8px] text-slate-500">{utc(last.timestamp_utc)}</p>:null}</div><div className="mt-3 grid grid-cols-2 gap-2"><Button data-testid="selected-focus-button" variant="outline" size="sm" className="font-mono text-[8px]" onClick={()=>{focusObject();if(!location.pathname.includes("dashboard"))navigate("/dashboard");}}><Crosshair size={11}/>FOCUS</Button><Button data-testid="orbit-visibility-button" variant="outline" size="sm" className="font-mono text-[8px]" onClick={()=>setOrbitVisible(!orbitVisible)}>{orbitVisible?<EyeOff size={11}/>:<Eye size={11}/>}{orbitVisible?"HIDE ORBIT":"SHOW ORBIT"}</Button><Button data-testid="selected-object-open-detail" variant="outline" size="sm" className="font-mono text-[8px]" onClick={()=>navigate(`/objects/${o.id}`)}>FULL DETAILS<ArrowUpRight size={11}/></Button><Button data-testid="selected-screen-button" size="sm" className="font-mono text-[8px]" onClick={()=>navigate("/conjunctions")}><ScanLine size={11}/>SCREEN</Button></div></div>:null}</div>}
  </aside>;
}