import { useEffect, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Link, NavLink, Outlet, useLocation, useNavigate } from "react-router-dom";
import { Radar, Satellite, Boxes, Orbit, TriangleAlert, Crosshair, ChartNoAxesCombined, Settings2, Search, ChevronDown, LogOut, UserRound, Menu, X, ArrowUpRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from "@/components/ui/dropdown-menu";
import { toast } from "sonner";
import { apiGet } from "@/lib/api";
import { endSession } from "@/lib/session";
import { useDebounced, useHealth } from "@/lib/data";
import type { AuthUser, OrbisObject } from "@/lib/orbis";
import { useOrbisStore } from "@/lib/store";

const navigation = [["/dashboard","Dashboard",Radar],["/objects","Objects",Boxes],["/satellites","Satellites",Satellite],["/debris","Debris",Orbit],["/conjunctions","Conjunctions",Crosshair],["/risk-analysis","Risk Analysis",TriangleAlert],["/aci-insights","ACI Insights",Radar],["/analytics","Analytics",ChartNoAxesCombined],["/settings","Settings",Settings2]] as const;

function UTCClock(){const health=useHealth();const [now,setNow]=useState("");useEffect(()=>{if(!health.data?.utc||health.isError){setNow("");return;}const anchor=Date.parse(health.data.utc),started=performance.now();const update=()=>setNow(new Date(anchor+performance.now()-started).toISOString().slice(11,19));update();const timer=setInterval(update,1000);return()=>clearInterval(timer);},[health.data?.utc,health.isError]);return <div data-testid="utc-clock" className="hidden font-mono text-[10px] text-slate-300 sm:block"><span className="mr-2 text-slate-500">UTC</span>{now||"UNAVAILABLE"}</div>;}

function GlobalSearch(){
  const [text,setText]=useState("");const query=useDebounced(text);const navigate=useNavigate();const setSelected=useOrbisStore(s=>s.setSelectedObject);
  const result=useQuery({queryKey:["global-search",query],queryFn:()=>apiGet<{results:OrbisObject[]}>(`/search?q=${encodeURIComponent(query)}&limit=7`),enabled:query.trim().length>1,staleTime:20000,retry:false});
  return <div className="relative w-full max-w-[350px]"><Search size={13} className="pointer-events-none absolute left-3 top-2.5 text-slate-500"/><Input data-testid="global-search-input" aria-label="Search catalog" value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Escape")setText("");}} placeholder="Search objects, name or NORAD ID" className="h-8 border-slate-700/60 bg-[#080f18] pl-9 text-[11px] placeholder:text-slate-500"/>{text.length>1?<div data-testid="global-search-results" className="absolute inset-x-0 top-10 z-50 max-h-80 overflow-y-auto rounded border border-slate-700 bg-[#0c1723] p-1 shadow-xl">{result.isError?<p data-testid="global-search-error" className="p-3 text-xs text-red-300">DATA UNAVAILABLE</p>:result.isFetching||query!==text?<p data-testid="global-search-loading" className="p-3 text-xs text-slate-400">SEARCHING CATALOG…</p>:result.data?.results.length?result.data.results.map(o=><button data-testid={`global-search-result-${o.id}`} key={o.id} onClick={()=>{setSelected(o.id);setText("");navigate("/dashboard");}} className="flex w-full items-center justify-between gap-2 rounded-sm p-3 text-left hover:bg-cyan-300/5"><div className="min-w-0"><div className="truncate text-xs text-slate-200">{o.name||"UNNAMED OBJECT"}</div><div className="mt-1 font-mono text-[9px] text-slate-500">{o.id} · {o.type}</div></div><ArrowUpRight size={12} className="text-cyan-300"/></button>):<p data-testid="global-search-empty" className="p-3 text-xs text-slate-400">No matching catalog objects.</p>}</div>:null}</div>;
}

export default function WorkstationShell(){
  const location=useLocation();const navigate=useNavigate();const [mobile,setMobile]=useState(false);const health=useHealth();const h=!health.isError?health.data:undefined;const user=useQuery({queryKey:["auth-me"],queryFn:()=>apiGet<AuthUser|null>("/auth/me"),retry:false});const {live,selectedObjectId}=useOrbisStore();
  const logout=useMutation({mutationFn:()=>endSession(),onError:()=>toast.error("Sign-out failed. Please retry.")});
  useEffect(()=>{setMobile(false);},[location.pathname]);
  const connected=!!h&&h.subsystems.backend!=="OFFLINE";const name=user.data?.name;
  return <div className="min-h-screen bg-[#060b12] text-slate-200">{mobile?<button data-testid="close-mobile-navigation-overlay" aria-label="Close navigation" className="fixed inset-0 z-40 bg-black/70 lg:hidden" onClick={()=>setMobile(false)}/>:null}
    <aside data-testid="sidebar-navigation" className={`fixed inset-y-0 left-0 z-50 flex w-[208px] flex-col border-r border-[#1a2938] bg-[#09111b] ${mobile?"":"hidden lg:flex"}`}><Link data-testid="orbis-logo-link" to="/dashboard" className="flex h-[76px] items-center gap-3 border-b border-slate-800/70 px-5"><div className="relative grid h-9 w-9 place-items-center rounded-full border border-cyan-300/40"><Orbit size={25} className="text-cyan-200"/><span className="absolute -right-1 top-2 h-1.5 w-1.5 rounded-full bg-cyan-200"/></div><div><div data-testid="orbis-logo-label" className="font-heading text-[23px] font-medium tracking-[.2em] text-slate-100">ORBIS</div><div className="mt-0.5 font-mono text-[6px] tracking-[.25em] text-slate-500">ORBITAL INTELLIGENCE</div></div></Link>
      <div className="px-5 pb-3 pt-7 font-mono text-[8px] tracking-[.18em] text-slate-500">OPERATIONS CONSOLE</div><nav className="space-y-1 px-3">{navigation.map(([path,label,Icon],index)=><NavLink data-testid={`nav-${label.toLowerCase().replaceAll(" ","-")}`} to={path} key={path} end={path==="/objects"} className={({isActive})=>`relative flex items-center gap-3 rounded-sm px-3 py-2.5 text-[11px] ${isActive?"bg-[#11303d]/70 text-cyan-200 before:absolute before:inset-y-2 before:left-0 before:w-0.5 before:bg-cyan-300":"text-slate-400 hover:bg-[#101e2b] hover:text-slate-200"}`}><Icon size={15} strokeWidth={1.5}/><span>{label}</span><span className="ml-auto font-mono text-[8px] opacity-30">0{index+1}</span></NavLink>)}</nav>
      <div className="mx-5 mt-auto border-t border-slate-800 pb-5 pt-4"><div data-testid="sidebar-system-status" className={`flex items-center gap-2 font-mono text-[8px] tracking-wider ${connected?"text-emerald-300":"text-amber-300"}`}><span className="h-1.5 w-1.5 rounded-full bg-current"/>{health.isLoading?"CONNECTING":connected?"BACKEND CONNECTED":"BACKEND OFFLINE"}</div><div data-testid="sidebar-api-status" className="mt-2 text-[9px] leading-5 text-slate-500">Python scientific core<br/>SGP4 / ACI / ML / SP3</div><div className="mt-5 flex justify-between font-mono text-[8px] text-slate-600"><span>SIH 2026</span><span>LOCAL DEMO</span></div></div>
    </aside><main className="min-w-0 lg:pl-[208px]"><header data-testid="top-bar" className="sticky top-0 z-30 flex h-[57px] items-center gap-4 border-b border-[#1b2a39] bg-[#0a121c]/95 px-4 backdrop-blur-lg lg:px-6"><Button data-testid="mobile-navigation-toggle" title="Navigation" variant="ghost" size="icon-sm" className="lg:hidden" onClick={()=>setMobile(!mobile)}>{mobile?<X size={17}/>:<Menu size={17}/>}</Button><div className="hidden min-w-0 flex-1 xl:block"><div data-testid="system-full-name" className="truncate font-mono text-[9px] tracking-[.12em] text-slate-400">ORBITAL RISK & BEHAVIOUR INTELLIGENCE SYSTEM</div></div><div className="flex min-w-0 flex-1 items-center gap-4 xl:flex-none"><GlobalSearch/><UTCClock/></div><div className="hidden h-5 w-px bg-slate-800 md:block"/><div data-testid="live-status" className={`hidden items-center gap-1.5 font-mono text-[8px] md:flex ${!connected?"text-red-300":live?"text-emerald-300":"text-amber-300"}`}><span className="h-1 w-1 rounded-full bg-current"/>{!connected?"OFFLINE":live?"LIVE":"REPLAY"}</div><DropdownMenu><DropdownMenuTrigger data-testid="user-profile-button" className="flex shrink-0 items-center gap-2 outline-none"><div className="grid h-7 w-7 place-items-center rounded-sm border border-slate-600/50 bg-[#172632] font-mono text-[10px] text-cyan-100">{name?.split(" ").map(n=>n[0]).slice(0,2).join("")||"—"}</div><span data-testid="user-profile-name" className="hidden max-w-32 truncate text-[11px] text-slate-200 sm:inline">{name||"SESSION UNAVAILABLE"}</span><ChevronDown size={11} className="text-slate-500"/></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-52"><div data-testid="profile-dropdown-identity" className="border-b border-slate-700 px-2 pb-3 pt-1"><div className="text-xs">{name}</div><div className="mt-1 text-[9px] text-slate-400">LOCAL DEMO AUTH</div></div><DropdownMenuItem data-testid="profile-menu-profile" onClick={()=>navigate("/settings")}><UserRound size={13}/>Profile</DropdownMenuItem><DropdownMenuItem data-testid="profile-menu-settings" onClick={()=>navigate("/settings")}><Settings2 size={13}/>Settings</DropdownMenuItem><DropdownMenuItem data-testid="logout-button" disabled={logout.isPending} onClick={()=>logout.mutate()}><LogOut size={13}/>Logout</DropdownMenuItem></DropdownMenuContent></DropdownMenu></header>
    {selectedObjectId?<div data-testid="selected-object-indicator" className="flex justify-end border-b border-slate-800/60 bg-cyan-500/[.025] px-6 py-1 font-mono text-[8px] text-slate-400">ACTIVE OBJECT <span className="ml-2 text-cyan-200">{selectedObjectId}</span></div>:null}<div className="mx-auto max-w-[2200px] p-4 lg:p-6"><Outlet/></div></main></div>;
}