import { useQuery } from "@tanstack/react-query";
import { useNavigate, useSearchParams } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { apiGet } from "@/lib/api";
import { useDebounced, useSummary } from "@/lib/data";
import { useOrbisStore } from "@/lib/store";
import type { PaginatedObjects } from "@/lib/orbis";
import { PageHeader, ObjectTable, DataState, EmptyState } from "@/components/ConsolePrimitives";

export default function CatalogWorkspace({mode="all"}:{mode?:"all"|"Satellite"|"Debris"}){
  const [params,setParams]=useSearchParams();const navigate=useNavigate();const setSelected=useOrbisStore(s=>s.setSelectedObject);const summary=useSummary();
  const page=Math.max(1,Number(params.get("page"))||1),text=params.get("search")||"",search=useDebounced(text),type=mode==="all"?params.get("type")||"":mode,decision=params.get("decision")||"",ml=params.get("ml_prediction")||"",sort=params.get("sort")||"id",order=params.get("order")||"asc";
  const query=useQuery({queryKey:["objects",mode,page,search,type,decision,ml,sort,order],queryFn:()=>apiGet<PaginatedObjects>(`/objects?page=${page}&limit=40&search=${encodeURIComponent(search)}&object_type=${type}&decision=${decision}&ml_prediction=${ml}&sort=${sort}&order=${order}`),retry:false});
  const update=(key:string,value:string)=>{const p=new URLSearchParams(params);value?p.set(key,value):p.delete(key);if(key!=="page")p.delete("page");setParams(p);};
  const s=!summary.isError?summary.data:undefined;const count=mode==="Satellite"?s?.satellites:mode==="Debris"?s?.debris:s?.total_objects;const data=!query.isError?query.data:undefined;
  return <div data-testid={`${mode.toLowerCase()}-page`} className="fade-enter"><PageHeader eyebrow={`CATALOG / ${mode==="all"?"ALL OBJECTS":mode.toUpperCase()}`} title={mode==="all"?"Object catalog":mode==="Satellite"?"Satellite surveillance":"Debris surveillance"} description="Authoritative catalog. Server-side filtering and sorting; 40 objects per page." action={<div data-testid="catalog-total-count" className={`font-mono text-xl ${mode==="Debris"?"text-amber-200":"text-cyan-200"}`}>{count?.toLocaleString()??"—"}<span className="ml-2 text-[9px] text-slate-500">CATALOG OBJECTS</span></div>}/>
    <section className="console-panel"><div className="grid gap-2 border-b border-slate-800 p-4 sm:grid-cols-2 xl:grid-cols-[minmax(180px,1fr)_130px_140px_165px_140px_100px]"><Input data-testid="object-search-input" aria-label="Search objects" placeholder="Search ID or object name" value={text} onChange={e=>update("search",e.target.value)} className="h-[38px] text-xs"/><select data-testid="type-filter-select" aria-label="Object type" disabled={mode!=="all"} value={type} onChange={e=>update("type",e.target.value)} className="console-input"><option value="">All types</option><option>Satellite</option><option>Debris</option></select><select data-testid="decision-filter-select" aria-label="ACI decision" value={decision} onChange={e=>update("decision",e.target.value)} className="console-input"><option value="">All decisions</option><option>FAST</option><option>DEEP</option><option>INSUFFICIENT_DATA</option></select><select data-testid="ml-filter-select" aria-label="ML classification" value={ml} onChange={e=>update("ml_prediction",e.target.value)} className="console-input"><option value="">All ML states</option><option>RELIABLE</option><option>LOW_CONFIDENCE</option></select><select data-testid="catalog-sort-select" aria-label="Sort catalog" value={sort} onChange={e=>update("sort",e.target.value)} className="console-input">{[["id","Catalog ID"],["name","Name"],["aci","ACI"],["model_confidence","Confidence"],["data_age","Data age"],["type","Type"]].map(([v,label])=><option key={v} value={v}>{label}</option>)}</select><select data-testid="catalog-sort-order" aria-label="Sort direction" value={order} onChange={e=>update("order",e.target.value)} className="console-input"><option value="asc">Ascending</option><option value="desc">Descending</option></select></div><div className="px-4 pt-3"><DataState error={query.isError} loading={query.isLoading} retry={()=>query.refetch()}/></div>{data?.objects.length?<ObjectTable objects={data.objects} onSelect={id=>{setSelected(id);navigate(`/objects/${id}`);}}/>:!query.isLoading&&!query.isError?<EmptyState message="No objects match the selected filters."/>:null}<div className="flex flex-wrap items-center justify-between gap-3 p-4"><div data-testid="catalog-count" className="font-mono text-[10px] text-slate-400">{data?.total.toLocaleString()??"—"} MATCHES <span className="ml-4 text-slate-500">PAGE {page} / {data?.total_pages||"—"}</span></div><div className="flex gap-2"><Button data-testid="catalog-previous-button" variant="outline" size="sm" disabled={page<=1} onClick={()=>update("page",String(page-1))}>Previous</Button><Button data-testid="catalog-next-button" variant="outline" size="sm" disabled={!data||page>=data.total_pages} onClick={()=>update("page",String(page+1))}>Next</Button></div></div></section><p data-testid="catalog-source-note" className="mt-4 font-mono text-[9px] text-slate-500">SOURCE / LIVE BACKEND · ACI OUTPUT CATALOG · N/A PREDICTION ERROR: NO VALID LIVE/REFERENCE COMPARISON</p>
  </div>;
}