import { Link, useSearchParams } from "react-router-dom";
import { useEffect, useMemo } from "react";
import { useQuery } from "@tanstack/react-query";
import { ArrowUpRight, Database, ShieldCheck } from "lucide-react";
import { apiGet } from "@/lib/api";
import type { PaginatedObjects, ScreeningResult } from "@/lib/orbis";
import { useSummary, useHealth, usePositions, useObjectData, number, percent } from "@/lib/data";
import { useOrbisStore } from "@/lib/store";
import { MetricCard, Panel, PageHeader, StatusChip, DataState } from "@/components/ConsolePrimitives";
import EarthGlobe from "@/components/EarthGlobe";
import ObjectIntelligence from "@/components/ObjectIntelligence";
import TelemetryConsole from "@/components/TelemetryConsole";

export default function CommandDashboard(){
  const [params,setParams]=useSearchParams();const {selectedObjectId,setSelectedObject}=useOrbisStore();const summary=useSummary(),health=useHealth(),positions=usePositions();const data=useObjectData(selectedObjectId);const s=!summary.isError?summary.data:undefined;const h=!health.isError?health.data:undefined;
  useEffect(()=>{const id=params.get("object");if(id&&id!==useOrbisStore.getState().selectedObjectId)setSelectedObject(id);},[params,setSelectedObject]);
  const recent=useQuery({queryKey:["recent-objects"],queryFn:()=>apiGet<PaginatedObjects>("/objects?limit=5&sort=data_age&order=asc"),staleTime:30000,retry:false});
  const screen=useQuery({queryKey:["screen-result",selectedObjectId],queryFn:async()=>null as ScreeningResult|null,enabled:false});
  const highlights=useMemo(()=>screen.data?[...screen.data.results.filter(r=>r.status==="POTENTIAL_CONJUNCTION").map(r=>r.object_id),...(screen.data.status==="POTENTIAL_CONJUNCTION"?[screen.data.target_id]:[])]:[],[screen.data]);
  const select=(id:string)=>{setSelectedObject(id);setParams({object:id},{replace:true});};
  const cards=[{label:"Total objects",value:s?.total_objects,href:"/objects",hint:"Cataloged objects",tone:"cyan"},{label:"Satellites",value:s?.satellites,href:"/satellites",hint:"Tracked spacecraft",tone:"cyan"},{label:"Debris",value:s?.debris,href:"/debris",hint:"Orbital fragments",tone:"amber"},{label:"FAST",value:s?.fast,href:"/objects?decision=FAST",hint:"ACI ≥ 0.70",tone:"green"},{label:"DEEP",value:s?.deep,href:"/objects?decision=DEEP",hint:"ACI < 0.70",tone:"amber"},{label:"Reliable",value:s?.reliable,href:"/objects?ml_prediction=RELIABLE",hint:"ML classification",tone:"green"},{label:"Low confidence",value:s?.low_confidence,href:"/objects?ml_prediction=LOW_CONFIDENCE",hint:"ML classification",tone:"amber"}] as const;
  return <div data-testid="dashboard-page" className="fade-enter"><PageHeader eyebrow="MISSION CONTROL / OVERVIEW" title="Orbital surveillance" description="A connected view of the orbital environment. Real catalog evidence. Authoritative scientific intelligence." action={<div data-testid="dashboard-source-badge" className="flex items-center gap-2 rounded-sm border border-cyan-300/15 bg-cyan-300/[.025] px-3 py-2 font-mono text-[8px] tracking-wider text-cyan-200"><Database size={12}/>{s?"LIVE BACKEND / CATALOG":"CONNECTING TO ORBIS BACKEND"}</div>}/>
    <DataState error={summary.isError} loading={summary.isLoading} retry={()=>summary.refetch()}/>{summary.error instanceof Error&&summary.error.message.includes("INTEGRITY")?<div data-testid="integrity-error" className="mb-3 border border-red-400/30 p-3 font-mono text-xs text-red-300">{summary.error.message}</div>:null}
    <div data-testid="dashboard-stat-grid" className="grid grid-cols-2 gap-2.5 md:grid-cols-4 xl:grid-cols-7">{cards.map(c=><Link key={c.label} data-testid={`stat-link-${c.label.toLowerCase().replaceAll(" ","-")}`} to={c.href}><MetricCard label={c.label} value={c.value??"—"} hint={c.hint} tone={c.tone}/></Link>)}</div>
    <div className="mission-grid mt-4"><div className="min-w-0 space-y-3"><section className="console-panel overflow-hidden"><div className="flex items-center justify-between gap-3 border-b border-slate-800 px-4 py-3"><div><span data-testid="orbital-environment-title" className="text-[12px] text-slate-200">Orbital environment</span><span className="ml-3 hidden font-mono text-[8px] tracking-wider text-slate-500 sm:inline">EARTH-CENTERED / EARTH-FIXED</span></div><span data-testid="globe-track-count" className="font-mono text-[8px] text-cyan-200">{!positions.isError&&positions.data?`${positions.data.valid.filter(v=>v===1).length.toLocaleString()} VALID SGP4 STATES`:"PROPAGATING CATALOG"}</span></div>{screen.data?<div data-testid="screening-overlay-note" className="border-b border-slate-800 px-4 py-1 font-mono text-[8px] text-amber-200">SAVED SCREENING OVERLAY / {screen.data.timestamp_utc} · RED = RETURNED TOP-N POTENTIAL PAIRS, NOT LIVE RISK</div>:null}<DataState error={positions.isError} retry={()=>positions.refetch()}/><EarthGlobe positions={!positions.isError?positions.data:undefined} onSelect={select} current={data.current} trajectory={!data.trajectory.isError?data.trajectory.data:undefined} highlights={highlights}/></section><TelemetryConsole data={data} compact/>
      <div data-testid="data-integrity-strip" className="flex flex-wrap items-center gap-x-5 gap-y-2 px-1 py-2 font-mono text-[8px] text-slate-500"><span className="flex items-center gap-1.5 text-slate-300"><ShieldCheck size={12}/> DATA INTEGRITY</span><span>CATALOG <b className="font-normal text-slate-300">{s?"RECONCILED":"UNAVAILABLE"}</b></span><span>PROPAGATION <b className="font-normal text-slate-300">SGP4</b></span><span>CONFIDENCE <b className="font-normal text-slate-300">ACI / ML</b></span><span>SCREENING <b className="font-normal text-slate-300">GEOMETRIC ONLY</b></span></div>
    </div><ObjectIntelligence data={data}/></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1.7fr)_minmax(0,1fr)_minmax(0,.9fr)]"><Panel title="Catalog watch" eyebrow="MOST RECENT TLE EVIDENCE" action={<Link data-testid="dashboard-view-catalog" to="/objects" className="flex items-center gap-1 text-[9px] text-cyan-200">Catalog<ArrowUpRight size={11}/></Link>}><DataState error={recent.isError} loading={recent.isLoading} retry={()=>recent.refetch()}/><div className="overflow-x-auto"><table className="w-full text-left text-[10px]"><thead className="technical-label"><tr><th className="pb-3 font-normal">OBJECT</th><th className="pb-3 font-normal">ACI</th><th className="pb-3 font-normal">DECISION</th><th className="pb-3 text-right font-normal">AGE</th></tr></thead><tbody>{!recent.isError?recent.data?.objects.map(o=><tr data-testid={`recent-object-${o.id}`} key={o.id} className="border-t border-slate-800/60"><td className="max-w-44 py-2"><button data-testid={`select-recent-${o.id}`} onClick={()=>select(o.id)} className="max-w-full truncate text-slate-200 hover:text-cyan-200">{o.name||o.id}<span className="ml-2 font-mono text-[8px] text-slate-500">{o.id} · {o.type}</span></button></td><td className="font-mono text-cyan-200">{number(o.aci,3)}</td><td><StatusChip value={o.decision}/></td><td className="text-right font-mono text-slate-400">{number(o.data_age_days,1," d")}</td></tr>):null}</tbody></table></div></Panel>
    <Panel title="Confidence envelope" eyebrow="ACI / PROTOTYPE ML"><div className="space-y-5">{[["MEAN ACI",number(s?.aci.mean,3),s?.aci.mean,"#67c2d0"],["MEAN MODEL CONFIDENCE",percent(s?.model_confidence.mean),s?.model_confidence.mean,"#81b8a8"]].map(([label,value,ratio,color])=><div key={String(label)} data-testid={`confidence-${String(label).toLowerCase().replaceAll(" ","-")}`}><div className="flex justify-between text-[10px]"><span className="technical-label">{label}</span><span className="font-mono text-slate-200">{value}</span></div><div className="mt-2 h-1 bg-slate-800"><div className="h-1" style={{width:typeof ratio==="number"?`${Math.min(100,Math.max(0,ratio*100))}%`:"0%",background:String(color)}}/></div></div>)}<p data-testid="dashboard-confidence-disclaimer" className="text-[10px] leading-5 text-slate-500">Confidence in evidence, not collision probability. ACI ≥ 0.70 supports FAST analysis.</p><Link data-testid="dashboard-aci-link" to="/aci-insights" className="block border-t border-slate-800 pt-3 font-mono text-[9px] text-cyan-200">EXPLORE ACI INSIGHTS ↗</Link></div></Panel>
    <Panel title="System health" eyebrow="SCIENTIFIC SUBSYSTEMS"><div data-testid="subsystem-matrix" className="space-y-2">{["backend","dataset","sgp4","aci","ml","sp3"].map(key=><div data-testid={`subsystem-row-${key}`} key={key} className="flex justify-between border-b border-slate-800/50 pb-2"><span className="font-mono text-[9px] uppercase text-slate-400">{key}</span><StatusChip value={h?.subsystems[key]||"OFFLINE"}/></div>)}</div></Panel></div>
  </div>;
}