import { useEffect } from "react";
import { useParams, Link } from "react-router-dom";
import { useObjectData, number, utc } from "@/lib/data";
import { useOrbisStore } from "@/lib/store";
import { PageHeader, Panel, DetailValue, StatusChip, DataState } from "@/components/ConsolePrimitives";
import EarthGlobe from "@/components/EarthGlobe";
import ObjectIntelligence from "@/components/ObjectIntelligence";
import TelemetryConsole from "@/components/TelemetryConsole";

export default function ObjectWorkspace(){const {id=""}=useParams();const setSelected=useOrbisStore(s=>s.setSelectedObject);useEffect(()=>{if(useOrbisStore.getState().selectedObjectId!==id)setSelected(id);},[id,setSelected]);const data=useObjectData(id);const o=!data.object.isError?data.object.data:undefined;const state=data.current;
  return <div data-testid="object-detail-page" className="fade-enter"><PageHeader eyebrow={`OBJECT WORKSPACE / ${id}`} title={o?.name||id} description="Identity, orbital state, reliability and telemetry. Every scientific readout is returned by the Python backend." action={<Link data-testid="object-detail-back-link" to="/objects" className="font-mono text-[10px] text-cyan-200">← OBJECT CATALOG</Link>}/><DataState error={data.object.isError} loading={data.object.isLoading} message="ACQUIRING OBJECT" retry={()=>data.object.refetch()}/><div className="mission-grid"><div className="min-w-0 space-y-4"><section className="console-panel overflow-hidden"><div data-testid="trajectory-status" className="flex justify-between border-b border-slate-800 px-4 py-3 font-mono text-[9px] text-slate-400"><span>ACTUAL PROPAGATED TRAJECTORY / SGP4</span><span>{!data.trajectory.isError?data.trajectory.data?.samples.length??"—":"UNAVAILABLE"} SAMPLES</span></div><EarthGlobe onSelect={setSelected} current={state} trajectory={!data.trajectory.isError?data.trajectory.data:undefined}/></section><DataState error={data.state.isError||data.trajectory.isError} retry={()=>{data.state.refetch();data.trajectory.refetch();}}/><Panel title="Current propagated state" eyebrow="SGP4 / TEME + EARTH-FIXED"><div data-testid="object-current-utc" className="mb-3 flex flex-wrap items-center gap-3 font-mono text-[9px] text-slate-400">{utc(state?.utc)}<StatusChip value={state?.sgp4_status}/></div><div data-testid="state-grid" className="grid grid-cols-2 gap-3 md:grid-cols-4">{[["Latitude",number(state?.latitude_deg,4,"°")],["Longitude",number(state?.longitude_deg,4,"°")],["Altitude",number(state?.altitude_km,3," km")],["Speed",number(state?.speed_km_s,4," km/s")]].map(([label,value])=><div key={label} data-testid={`state-readout-${label.toLowerCase()}`} className="border-l border-slate-700 pl-3"><div className="technical-label">{label}</div><div className="mt-2 font-mono text-sm text-cyan-100">{value}</div></div>)}</div></Panel><TelemetryConsole data={data}/><Panel title="Identity & source record" eyebrow="ORIGINAL CATALOG / TLE"><div className="grid gap-3 sm:grid-cols-3"><DetailValue label="Catalog ID" value={o?.id||"N/A"}/><DetailValue label="Classification" value={o?.type||"N/A"}/><DetailValue label="TLE epoch" value={o?.epoch||"N/A"}/></div><div data-testid="tle-line-one" className="mt-4 break-all font-mono text-[11px] leading-6 text-slate-300">{o?.tle_line1||"DATA UNAVAILABLE"}</div><div data-testid="tle-line-two" className="break-all font-mono text-[11px] leading-6 text-slate-300">{o?.tle_line2}</div></Panel></div><ObjectIntelligence data={data}/></div></div>;
}