import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { apiGet } from "@/lib/api";
import { useHistory, useObjectData, number, percent } from "@/lib/data";
import { useOrbisStore } from "@/lib/store";
import type { PaginatedObjects } from "@/lib/orbis";
import { PageHeader, Panel, StatusChip, DataState } from "@/components/ConsolePrimitives";
import ObjectIntelligence, { ReliabilityContext } from "@/components/ObjectIntelligence";

export default function RiskWorkspace(){const {selectedObjectId,setSelectedObject}=useOrbisStore();const data=useObjectData(selectedObjectId);const history=useHistory();const objects=useQuery({queryKey:["risk-objects"],queryFn:()=>apiGet<PaginatedObjects>("/objects?limit=20&sort=aci&order=asc"),retry:false});return <div data-testid="risk-analysis-page" className="fade-enter"><PageHeader eyebrow="EVIDENCE REVIEW / OPERATIONAL CONTEXT" title="Risk analysis" description="Review confidence and reliability separately from geometric orbital separation. Unscreened objects are never marked clear."/><div className="mission-grid"><div className="min-w-0 space-y-4"><ReliabilityContext/><Panel title="Evidence requiring attention" eyebrow="BACKEND CATALOG / LOWEST ACI FIRST"><DataState error={objects.isError} loading={objects.isLoading} retry={()=>objects.refetch()}/><div data-testid="risk-object-list" className="overflow-x-auto"><table className="w-full min-w-[670px] text-left text-[10px]"><thead className="technical-label"><tr>{["Object","ACI / decision","ML confidence","Age / consistency","Screening"].map(label=><th key={label} className="px-2 pb-3 font-normal">{label}</th>)}</tr></thead><tbody>{!objects.isError?objects.data?.objects.map(o=>{const last=!history.isError?history.data?.items.find(h=>h.target_id===o.id):undefined;return <tr key={o.id} data-testid={`risk-object-${o.id}`} className="border-t border-slate-800"><td className="max-w-36 px-2 py-3"><button data-testid={`select-risk-object-${o.id}`} onClick={()=>setSelectedObject(o.id)} className="text-left text-cyan-200 hover:underline">{o.name||o.id}</button><div className="mt-1 font-mono text-[8px] text-slate-500">{o.id} · {o.type}</div></td><td className="px-2"><div className="mb-1 font-mono text-slate-200">{number(o.aci,3)}</div><StatusChip value={o.decision}/></td><td className="px-2"><div className="mb-1 font-mono text-cyan-100">{percent(o.model_confidence)}</div><StatusChip value={o.ml_prediction}/></td><td className="px-2 font-mono leading-6 text-slate-400">{number(o.data_age_days,1," d")}<br/>{number(o.trajectory_consistency,3)}</td><td className="px-2"><StatusChip value={last?.status||"NOT_SCREENED"}/>{last?<Link data-testid={`risk-history-${o.id}`} to={`/conjunctions/history?screening=${last.screening_id}`} className="mt-1 block text-[8px] text-slate-500 underline">Saved screening, not live</Link>:null}</td></tr>;}):null}</tbody></table></div></Panel></div><ObjectIntelligence data={data}/></div></div>;}